unstable_features = true
condense_wildcard_suffixes = true
reorder_imports = true
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
trailing_semicolon = true
use_field_init_shorthand = true